### ISSUE TITLE
Using nodemon in development for automatically restarting server

### ISSUE THREAD

**Issue by vinaypuppal** [DanyDin1801/Product-Portal#6]
I would suggest to use [nodemon](http://nodemon.io/) for development and add one more script to package.json "dev": "nodemon server.js". So we can run `npm run dev` on development machine and need not restart server manually whenever server side code changes.

**Comment by rhgksrua** [comment]
I would also go with `nodemon`.

**Comment by JordyVlassembrouck** [comment]
Nodemon does create some overhead though. When we change client side code, we don't want to restart the entire server. Right now, this won't be an issue when developing, but once we have a larger codebase, this can get annoying.
Is there any possibility to use Nodemon for Server side code only and use a live reload framework for client side code?

**Comment by vinaypuppal** [comment]
@JordyVlassembrouck read about nodemon features and docs [here](https://github.com/remy/nodemon)  you can ignore files or directories by providing options to `nodemon` . But i think we will run `nodemon server.js` so it will only watch `server.js` file and any files we import inside `server.js` file as far as i know. Just test it with sample project and let us know here if any issues we may have if we use `nodemon`

**Comment by JordyVlassembrouck** [comment]
@vinaypuppal Nodemon looks great for development. You'll have to create a server folder with the server.js file included, I reckon, and set a watcher on that folder to check all the files that run on the backend.
I'll create another issue to implement live reload.

**Comment by JordyVlassembrouck** [comment]
@vinaypuppal reviewed and approved :white_check_mark:

**Comment by vinaypuppal** [comment]
@rhgksrua @JordyVlassembrouck which would be better, moving `server.js` to `server/` folder and using `nodemon` to watch that folder or ignoring `public/`, `test/` and `html/` folders in `nodemon` process, so nodemon will watch entire root folder except files inside ignored folders. For me keeping server.js at root of project and ignoring client side folders seems better option. Any suggestions??

**Comment by arreche** [comment]
I would vote for moving the `server.js` into a `server/` directory... But I think that we don't need any kind of server reloading at this moment.

**Comment by rhgksrua** [comment]
We can move all server related files into `server/` directory.  But server reloading will make things a lot easier since we'll need to make some api endpoints for our server.

**Comment by vinaypuppal** [comment]
@rhgksrua i thought [this](https://www.terlici.com/2014/08/25/best-practices-express-structure.html) would be better file structure to follow. And yes nodemon would is optional, it is to make developer/developing experience better.

**Comment by rhgksrua** [comment]
You should create a new issue to talk about project structure.  I'm just saying we can have nodemon as a dev dependency and let people decide if they want to use it or not.

**Comment by JordyVlassembrouck** [comment]
@rhgksrua +1
@vinaypuppal It is a good practice to separate everything that you can. I would separate every server side code in server/ and client code in public/ or anything else. I also like your article about project structure. I'll take a closer look at it tomorrow and maybe we can work something out.

**Comment by vinaypuppal** [comment]
Merged and closed
